### ISSUE TITLE
Favourite toggle behaviour

### ISSUE THREAD

**Issue by utsavdevsharma** [astriskit/miniature-parakeet#2]
hi @astriskit , request you to explain your thought process on the behaviour of favourite toggle. As soon as you click a star, the rest of the stars get disabled. Why do we need to disable the rest of the stars?

Also the ui of the whole page is shifting as well, when we click on any star

**Comment by astriskit** [comment]
Hi @utsavdevsharma. It is done to change/toggle one post at a time. In case allowed, the racing condition is not yet built. So kept it simple for now.

Shifting-ui is a known bug - spinner causes it; But thanks for pointing out.
